### ISSUE TITLE
Login times out

### ISSUE THREAD

**Issue by Qwertie-** [Fxrh/Quaternion#106]
After building the latest version my login details fail and the login times out

On start up I get ```Job "PasswordLogin" status 103 : "Error transferring https://matrix.org/_matrix/client/r0/login - server replied: Forbidden"``` and a pop up asking for my details again.

After re entering my details I get

```
Job "PasswordLogin" created
Job "SyncJob-15" destroyed
Job "SyncJob-16" created
Job "PasswordLogin" destroyed
Job "SyncJob-16" status 102 : "The job has timed out"
Job "SyncJob-16" finishes without ready network reply
"The job has timed out"
```

Before todays commits login worked fine.

**Comment by KitsuneRal** [comment]
That doesn't look related to the recent commits: they haven't dealt with the network interaction or login stuff at all. Are you sure you don't have network issues? I can't reproduce this.
On the other hand, I happened to encounter that several times but it was clearly synapse glitching on the other side.

**Comment by Qwertie-** [comment]
Hm, seems to be working now, Didn't change anything so it must have been some weird network issue
