### ISSUE TITLE
QObject::connect: Cannot connect (null)::getPreviousContent() to ChatRoomWidget::getPreviousContent()

### ISSUE THREAD

**Issue by jjdredd** [Fxrh/Quaternion#119]
return value QQuickView::rootObject() returning null in chatroomwidget.cpp:94

Result of this is constantly blank middle chat widget

**Comment by jjdredd** [comment]
Result of this is constantly blank middle chat widge

**Comment by maralorn** [comment]
Hello @jjdredd,
thanks for the report. Can you tell us with which version of quaternion this happens? And which OS you use?

**Comment by jjdredd** [comment]
this happens on 46654835fbb817b50ecef71a72004c8d53db80bd
gentoo amd64 `Linux gentoocompdell 4.4.6-gentoo #9 SMP Fri Oct 14 21:42:22 MDT 2016 x86_64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz GenuineIntel GNU/Linux`

Qt versions

```
     Sat Aug 20 12:10:17 2016 >>> dev-qt/qtcore-5.6.1
     Sat Aug 20 12:11:10 2016 >>> dev-qt/qtnetwork-5.6.1
     Sat Aug 20 12:11:37 2016 >>> dev-qt/qttest-5.6.1
     Sat Aug 20 12:12:02 2016 >>> dev-qt/qtxml-5.6.1
     Sat Aug 20 12:12:30 2016 >>> dev-qt/linguist-tools-5.6.1
     Sat Aug 20 12:14:58 2016 >>> dev-qt/qtxmlpatterns-5.6.1
     Sat Aug 20 12:15:39 2016 >>> dev-qt/qtdbus-5.6.1
     Sat Aug 20 12:19:15 2016 >>> dev-qt/qtgui-5.6.1
     Sat Aug 20 12:21:54 2016 >>> dev-qt/qtwidgets-5.6.1
     Sat Aug 20 12:27:59 2016 >>> dev-qt/qtdeclarative-5.6.1-r1
```

**Comment by KitsuneRal** [comment]
@jjdredd please make sure the following is installed:
```
sudo apt-get install git cmake qtdeclarative5-dev qtdeclarative5-qtquick2-plugin qtdeclarative5-controls-plugin
```
I guess you're missing the plugins, specifically.

**Comment by jjdredd** [comment]
@KitsuneRal thanks, I'm not sure though how the packages are called. I will try and report back.

**Comment by KitsuneRal** [comment]
@jjdredd, sorry, didn't notice you're on Gentoo. As far as I can see, you would at least need dev-qt/qtquickcontrols. dev-qt/qtimageformats and, probably, dev-qt/qtsvg might improve visuals a bit but should not be required.

**Comment by jjdredd** [comment]
@KitsuneRal Thanks a lot, everything works now! Looks like it was my bad. Also the Qt docs don't specify when the mentioned method can return null.
By the way is there an option to hide the client to tray?

**Comment by KitsuneRal** [comment]
Qt docs are known to be not quite complete, especially when it comes to rough edges like missing parts. Actually, we put more accurate information regarding the needed packages into our own README.md - these changes will land in master within this week.

Do you mean to hide it from the taskbar?

**Comment by jjdredd** [comment]
Yes, hide the window and hide it from the taskbar, leaving only a small icon in the system tray.

**Comment by KitsuneRal** [comment]
No, as of right now.

**Comment by jjdredd** [comment]
Well, thanks for help.
