### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by jansol** [Fxrh/Quaternion#124]
NaChat is doing a remarkably good job at this, maybe borrow from it.

**Comment by KitsuneRal** [comment]
Uhm, which version of Quaternion are you on? Quaternion has clickable URLs since summer or something like that.

**Comment by elvisangelaccio** [comment]
hmm I can actually reproduce non-clickable links on the latest git master.

**Comment by elvisangelaccio** [comment]
Ok, latest master for sure has clickable **html** links (e.g. `<a href=\"http://example.org/\">link</a>` in the `formatted_body` key), but not if the url is *only* in the `body` key, for example:

```
 "body": "test url: http://example.org/"
```

**Comment by elvisangelaccio** [comment]
Btw plain urls in the room topic are also not clickable.

**Comment by KitsuneRal** [comment]
Yes, the reason of this is that Qt is able to render a subset of HTML, and that's exactly how some URLs are clickable - Quaternion just displays HTML content of the message. If there's only plain text content, it's just plain text, no URLs detection.
