### ISSUE TITLE
Dark theme compatibility

### ISSUE THREAD

**Issue by AnotherBugworm** [Fxrh/Quaternion#125]
![screenshot_20170221_173735](https://cloud.githubusercontent.com/assets/7214361/23171993/f0b85604-f85c-11e6-8a34-3ba2642f9e75.png)

**Comment by KitsuneRal** [comment]
What's the version/commit you're seeing this at? Dark themes are supported since October but there were no official releases with it yet.

**Comment by AnotherBugworm** [comment]
I'm using quaternion-git from AUR, so it probably the latest git version. Tried to update, nothing changes. Also happens with breeze dark, so it's not a theme or color scheme issue
![spectacle x27634](https://cloud.githubusercontent.com/assets/7214361/23322188/7e022860-faeb-11e6-9f97-97d6c9042cfa.png)

**Comment by KitsuneRal** [comment]
Ok, I double-checked - it's an apparent degradation, thanks for reporting.

**Comment by KitsuneRal** [comment]
Fixed by https://github.com/Fxrh/Quaternion/commit/d5a8e1bcc2bd82d7bba71e59db8126c341271772
