### ISSUE TITLE
[Feature Request] Add support for SailfishOS

### ISSUE THREAD

**Issue by rodneyrod** [Fxrh/Quaternion#148]

**Comment by KitsuneRal** [comment]
This will basically require making a different UI that uses QML but not QT Widgets. I'm not closing this right now but Tensor has much better chances to be ported to SailfishOS, compared to Quaternion. The backend of both projects is the same, it's libqmatrixclient; and UI in the QML part is somewhat related but other parts are totally different.

**Comment by rodneyrod** [comment]
Ahh, thanks for the explanation. Not too familiar with Qt UIs, I did ping the Tensor devs but I haven't heard anything back from them on the matter.

**Comment by KitsuneRal** [comment]
Well, as I'm one of Tensor contributors, I can repeat what either I or davidar said in #tensor sometime ago: patches are welcome but none of us has a Sailfish phone and capacity to implement support of one more platform. Initial analysis says that the effort shouldn't be that big; but now we need someone who'll actually make the thing work.

**Comment by rodneyrod** [comment]
I have a Sailfish OS phone and I can rig up a build environment in a VM, but my C style programming proficiency is minimal at best, and due to current situations I don't have any time to be improving that. I can offer what assistance I can though, and if needed, throw some donations towards development if needed.

**Comment by KitsuneRal** [comment]
Well, you don't really need C to program in QML, you need JavaScript. But the nearest step so far is to pack up something that would at least build and startup with Sailfish toolchain. Once this is done, we can go further.
Anyway, this discussion is for Tensor, not for Quaternion. So let's move to davidar/Tensor#4 with it.
