### ISSUE TITLE
remember last layout 

### ISSUE THREAD

**Issue by Gibbz** [Fxrh/Quaternion#160]
this is a rather frustrating one. But the app doesnt remember the last used layout. Each time it opens, you need to reset it up and get it all useable.

**Comment by KitsuneRal** [comment]
That's a bug because the code that saves docks position (you're talking about the docks layout, right?) is in place. Let me double-check if something got broken.

**Comment by Gibbz** [comment]
yep, so i move the rooms and users dock over ontop of each other so they form a tab view, and have them on the right.
When i open the app again, the docks are back in their original position/layout.

Thanks for quick response :)

**Comment by KitsuneRal** [comment]
That was an easy one. You should be good with c8235e3

**Comment by KitsuneRal** [comment]
And thanks for reporting!
