### ISSUE TITLE
Save login credentials

### ISSUE THREAD

**Issue by Fxrh** [Fxrh/Quaternion#27]

**Comment by Half-Shot** [comment]
Would it be better to save the token/refresh token rather the login details for security reasons?

**Comment by Fxrh** [comment]
Currently, this would work, as token are valid forever afaik, but I'm not sure this won't change.

**Comment by Half-Shot** [comment]
I thought a refresh token was sent alongside anyway? I believe the logic is all there even though it's pointless since the token is valid forever.

**Comment by KitsuneRal** [comment]
See #52.
