### ISSUE TITLE
Quaternion does not exit if window is closed

### ISSUE THREAD

**Issue by Fxrh** [Fxrh/Quaternion#31]
Connection->Quit does work, though

**Comment by KitsuneRal** [comment]
Seems to be fixed by dropping KCoreAddons - if not, please reopen.

**Comment by Fxrh** [comment]
It seems Quaternion was only properly quit if qApp->quit() was called. At least for me, the problem still exists if I just close the window, so unfortunately I have to reopen this...

**Comment by Fxrh** [comment]
I don't quite understand what's wrong here... I asked in the Qt forum: https://forum.qt.io/topic/71112/application-does-not-quit

**Comment by Fxrh** [comment]
Might be a Qt bug. c39e1f6c33edcc18c1b20c0f94f10503d1bfd828 has a workaround for this.
