### ISSUE TITLE
No rule to make target 'install'

### ISSUE THREAD

**Issue by Takios** [Fxrh/Quaternion#44]
Hey,

tried compiling following the documentation.
Compiling was successful, but `make install` does not work:

`make: *** No rule to make target 'install'.  Stop.`

I am in the build directory when issuing the command. 
The resulting binary works well, but the documentation states that make install should work. It's a bit confusing.

Greetings.

**Comment by KitsuneRal** [comment]
@Takios, what is your platform - Linux-x86?

**Comment by Takios** [comment]
x86_64. Distro is openSUSE Tumbleweed.

**Comment by Fxrh** [comment]
Hi Takios! Unfortunately, "make install" is not yet implemented, the documentation is wrong here.

@KitsuneRal Does Windows use make install, too? Or can I just write a "make install" for Linux?

**Comment by KitsuneRal** [comment]
The short answer is: "make install on Windows as it works on Linux doesn't make much sense" (pun unintended). I think the best way is to use CMake's `INSTALL(TARGETS)` - if you do it on your side for Linux, I can try to make something useful out of it for Windows. And we'll have to make somebody with OS X to check how much this works on his iron.
Sorry for not checking if the documentation is still relevant in that piece :(

**Comment by Fxrh** [comment]
Make install is in master
