### ISSUE TITLE
Auto-complete names by pressing tab

### ISSUE THREAD

**Issue by PureTryOut** [Fxrh/Quaternion#46]
Just like the Vector client. Basically currently pressing tab moves focus out of the chat line, but it should probably auto-complete the nickname you're typing instead.

**Comment by KitsuneRal** [comment]
Yes, this is most-wanted but not easy to implement properly. But yeah, probably it's time to take a bite.

**Comment by PureTryOut** [comment]
For some reason this wasn't closed automatically once #92 got merged. I guess the text "fixes #46" had to be in the initial PR message?
