### ISSUE TITLE
[Settings] Crash with multiple instances of Quaternion

### ISSUE THREAD

**Issue by Fxrh** [Fxrh/Quaternion#56]
1. Start the first instance, login, check "keep logged in"
2. Start the second instance, log out
3. After a few seconds, the first instance crashes.

Last lines of output:

<pre>
Job "SyncJob-9" status 103 : "Host requires authentication"

Thread 1 "quaternion" received signal SIGSEGV, Segmentation fault.
QScopedPointer<QMatrixClient::BaseJob::Private, QScopedPointerDeleter<QMatrixClient::BaseJob::Private> >::operator-> (this=0x10) at /usr/include/qt/QtCore/qscopedpointer.h:118
118             Q_ASSERT(d);
</pre>

Backtrace:
<pre>
#0  QScopedPointer<QMatrixClient::BaseJob::Private, QScopedPointerDeleter<QMatrixClient::BaseJob::Private> >::operator-> (this=0x10) at /usr/include/qt/QtCore/qscopedpointer.h:118
#1  0x0000000000470ee1 in QMatrixClient::BaseJob::finishJob (this=0x0, emitResult=false) at /home/felix/Development/qmatrixclient/lib/jobs/basejob.cpp:166
#2  0x0000000000471527 in QMatrixClient::BaseJob::abandon (this=0x0) at /home/felix/Development/qmatrixclient/lib/jobs/basejob.cpp:221
#3  0x00000000004564e4 in QMatrixClient::Connection::disconnectFromServer (this=0x8063b0) at /home/felix/Development/qmatrixclient/lib/connection.cpp:150
#4  0x0000000000442f00 in MainWindow::setConnection (this=0x7fffffffdcd0, newConnection=0x0) at /home/felix/Development/qmatrixclient/client/mainwindow.cpp:103
#5  0x00000000004434cf in MainWindow::loggedOut (this=0x7fffffffdcd0) at /home/felix/Development/qmatrixclient/client/mainwindow.cpp:183
#6  0x00000000004449da in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**) (f=(void (MainWindow::*)(MainWindow * const)) 0x443490 <MainWindow::loggedOut()>, o=0x7fffffffdcd0, arg=0x7fffffffcfd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:507
#7  0x0000000000444950 in QtPrivate::FunctionPointer<void (MainWindow::*)()>::call<QtPrivate::List<>, void>(void (MainWindow::*)(), MainWindow*, void**) (f=(void (MainWindow::*)(MainWindow * const)) 0x443490 <MainWindow::loggedOut()>, o=0x7fffffffdcd0, arg=0x7fffffffcfd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:526
#8  0x0000000000444886 in QtPrivate::QSlotObject<void (MainWindow::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x25367c0, r=0x7fffffffdcd0, a=0x7fffffffcfd0, ret=0x0) at /usr/include/qt/QtCore/qobject_impl.h:149
#9  0x00007ffff5ad785e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#10 0x0000000000479bc4 in QMatrixClient::Connection::loginError (this=0x8063b0, _t1=...) at /home/felix/Development/qmatrixclient/build/lib/moc_connection.cpp:389
#11 0x0000000000459258 in QMatrixClient::Connection::sync(int)::$_6::operator()() const (this=0x2ec7e20) at /home/felix/Development/qmatrixclient/lib/connection.cpp:181
#12 0x00000000004591d9 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, QMatrixClient::Connection::sync(int)::$_6>::call(QMatrixClient::Connection::sync(int)::$_6&, void**) (f=..., arg=0x7fffffffd210) at /usr/include/qt/QtCore/qobjectdefs_impl.h:501
#13 0x00000000004591b1 in QtPrivate::Functor<QMatrixClient::Connection::sync(int)::$_6, 0>::call<QtPrivate::List<>, void>(QMatrixClient::Connection::sync(int)::$_6&, void*, void**) (f=..., arg=0x7fffffffd210) at /usr/include/qt/QtCore/qobjectdefs_impl.h:558
#14 0x000000000045914d in QtPrivate::QFunctorSlotObject<QMatrixClient::Connection::sync(int)::$_6, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x2ec7e10, r=0x25d97a0, a=0x7fffffffd210, ret=0x0) at /usr/include/qt/QtCore/qobject_impl.h:198
#15 0x00007ffff5ad785e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#16 0x000000000047a2df in QMatrixClient::BaseJob::failure (this=0x25d97a0, _t1=0x25d97a0) at /home/felix/Development/qmatrixclient/build/lib/moc_basejob.cpp:235
#17 0x0000000000471148 in QMatrixClient::BaseJob::finishJob (this=0x25d97a0, emitResult=true) at /home/felix/Development/qmatrixclient/lib/jobs/basejob.cpp:182
#18 0x0000000000470cd4 in QMatrixClient::BaseJob::gotReply (this=0x25d97a0) at /home/felix/Development/qmatrixclient/lib/jobs/basejob.cpp:129
#19 0x0000000000472b8a in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QMatrixClient::BaseJob::*)()>::call(void (QMatrixClient::BaseJob::*)(), QMatrixClient::BaseJob*, void**) (f=(void (QMatrixClient::BaseJob::*)(QMatrixClient::BaseJob * const)) 0x470b30 <QMatrixClient::BaseJob::gotReply()>, o=0x25d97a0, arg=0x7fffffffd5a0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:507
#20 0x0000000000472b00 in QtPrivate::FunctionPointer<void (QMatrixClient::BaseJob::*)()>::call<QtPrivate::List<>, void>(void (QMatrixClient::BaseJob::*)(), QMatrixClient::BaseJob*, void**) (f=(void (QMatrixClient::BaseJob::*)(QMatrixClient::BaseJob * const)) 0x470b30 <QMatrixClient::BaseJob::gotReply()>, o=0x25d97a0, arg=0x7fffffffd5a0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:526
#21 0x0000000000472a36 in QtPrivate::QSlotObject<void (QMatrixClient::BaseJob::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x2ec14f0, r=0x25d97a0, a=0x7fffffffd5a0, ret=0x0) at /usr/include/qt/QtCore/qobject_impl.h:149
#22 0x00007ffff5ad785e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff5f7ee97 in ?? () from /usr/lib/libQt5Network.so.5
#24 0x00007ffff6015b59 in ?? () from /usr/lib/libQt5Network.so.5
#25 0x00007ffff5ad8349 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff76d4e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff76dc5b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff5aabc80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#29 0x00007ffff5aae3fd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#30 0x00007ffff5b00173 in ?? () from /usr/lib/libQt5Core.so.5
#31 0x00007ffff2829e67 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007ffff282a0d0 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff282a17c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007ffff5b0057f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff5aaa0da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff5ab25cc in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#37 0x000000000045310e in main (argc=1, argv=0x7fffffffdee8) at /home/felix/Development/qmatrixclient/client/main.cpp:52
</pre>

**Comment by KitsuneRal** [comment]
I got a crash with the same stack trace even on a single instance but without Internet connectivity. This is fixed by Fxrh/libqmatrixclient@0059072
