### ISSUE TITLE
Kick messages aren't displayed properly

### ISSUE THREAD

**Issue by PureTryOut** [Fxrh/Quaternion#66]
When a user is kicked, instead of saying he/she is kicked, Quaternion says they left the room. While this is true, it would be nicer to show they're kicked.

![screenshot_2016-09-19_12-16-10](https://cloud.githubusercontent.com/assets/1565836/18629032/63ff46dc-7e63-11e6-92d6-6f7debe31ea9.png)

The top is what Quaternion shows, the bottom what Vector shows.

**Comment by KitsuneRal** [comment]
This is addressed within #70

**Comment by KitsuneRal** [comment]
Merged in the mainline.
