### ISSUE TITLE
Remember input line status per room

### ISSUE THREAD

**Issue by maralorn** [Fxrh/Quaternion#82]
It’s very annoying, if you are typing get a highlight somewhere else, wan’t to quick reply, and then return to your previous discussion.

**Comment by ara4n** [comment]
heads up that on the Matrix side we are going to spec synced read marker 
support fairly soon.  Riot for instance currently tracks it per-device, 
rather than synced cross-device.

**Comment by maralorn** [comment]
I am not sure if this is directly related to what I mean’t. I was not referring to any read status but to a drafted message in the input line.
