### ISSUE TITLE
No reloading is triggered, when top of log is reached.

### ISSUE THREAD

**Issue by maralorn** [Fxrh/Quaternion#94]
When scrolling upwards, more history get’s pulled in. But I can scroll so fast upwards, that I reach the upper end of log where no reload get’s triggered. I actually have to bounce the view against the top again and again everytime I want to pull more history.

**Comment by KitsuneRal** [comment]
After some minor refactoring and experimenting I think I've found I way to make fetching historical messages so unobtrusive that you can scroll yourself away. The respective (very small) PR for libqmatrixclient is already submitted and hopefully will be merged soon; the Quaternion PR will follow shortly afterwards.
